### ISSUE TITLE
希望添加一些默认应用

### ISSUE THREAD

**Issue by panyuhang93** [RikkaApps/Riru-LocationReportEnabler#1]
com.google.android.googlequicksearchbox 谷歌搜索 显示feed
com.google.android.apps.nexuslauncher 谷歌启动器 显示天气
com.google.android.as Actions Services （疑似显示锁屏天气）

**Comment by RikkaW** [comment]
前两个肯定不需要（
第三个的话反正可以自定义嘛 自己增加确认之后再来要求增加默认呀（

**Comment by panyuhang93** [comment]
好吧
