### ISSUE TITLE
自定义gsm.sim.operator.numeric无效，google play读到的始终是310030

### ISSUE THREAD

**Issue by baraja** [RikkaApps/Riru-LocationReportEnabler#10]
bug重现步骤：
1、magisk安装Riru-LocationReportEnabler模块
2、自定义为310260
3、清空google play store数据，再打开
4、pc端访问https://play.google.com/settings/，显示当前运营商为AT&T（应该是T-mobile，如果用location report enabler的root版会显示成这个）
5、完全卸载riru相关模块，清空google play store数据
6、pc端访问https://play.google.com/settings/，显示当前运营商为国内的
7、完全卸载riru相关模块，直接编辑magisk-riru-location-report-enabler-arm-arm64-v3.zip里面的gsm.sim.operator.numeric为310260，再次刷入编辑后的模块
8、https://play.google.com/settings/显示运营商为AT&T（修改后依然不工作）

**Comment by RikkaW** [comment]
模块改成了什么直接看 tag 是 LocationReportEnabler 的 log
比如这样的
```
I/LocationReportEnabler: android::base::GetProperty: gsm.sim.operator.numeric -> 310260
```

这边改了 310260 试了一下发现没有问题，至于 Google Play 那边觉得是什么那是 Google 的事

**Comment by baraja** [comment]
感谢回复，麻烦请再检查一下是不是写死310030了，因为我看源码里面
Riru-LocationReportEnabler-master\jni\main\hook.cpp
这个里面有一条
`static const char *sim_operator_numeric = "310030";`

**Comment by RikkaW** [comment]
你倒是自己看看自己的 log
另外接着往下就有 `set_sim_operator_numeric` 会在 main.cpp 的 `load_config` 里面被用

**Comment by baraja** [comment]
> 你倒是自己看看自己的 log
> 另外接着往下就有 `set_sim_operator_numeric` 会在 main.cpp 的 `load_config` 里面被用

抱歉，我不知道如何查看log，请指教
另外我使用的版本是v3进行测试的，最新的v6因为打不开地图时间轴，只能弃用。
新的测试结果如下：
使用hex编辑器直接修改v3包里的两个libriru_location_report_enabler.so
310030替换为310260，
再进google play，显示为T-mobile US了
如此看来v3是写死在源码里了，自定义是无效的？
v6没有测试，不知是否有效。

再次感谢提供这么好的软件，比root版的LRE方便很多，因为不会替换系统界面里的APN，切换sim卡时尤其方便，谢谢！

**Comment by oit63** [comment]
感谢，v10 版本的替换 customize.sh 和 customize.sh.sha256sum
修改 customize.sh 中这两句话
if [ ! -d "$CONFIG_PATH/properties" ]; then
    ui_print "- Creating default configuration (1)"
    mkdir -p "$CONFIG_PATH/properties"
    echo -n "310030" > "$CONFIG_PATH/properties/gsm.sim.operator.numeric"
    echo -n "us" > "$CONFIG_PATH/properties/gsm.sim.operator.iso-country"
fi

`
    echo -n "310260,310260" > "$CONFIG_PATH/properties/gsm.sim.operator.numeric"
`
`
    echo -n "us,us" > "$CONFIG_PATH/properties/gsm.sim.operator.iso-country"
`
Xperia 1 dual(J9110)（双卡机），亲测有效
