### ISSUE TITLE
希望增加双卡支持

### ISSUE THREAD

**Issue by mclovin-2k** [RikkaApps/Riru-LocationReportEnabler#12]
双卡的gsm.sim.operator.numeric 和 gsm.sim.operator.iso-country 多了一个逗号。例如：
gsm.sim.operator.numeric = 310030,310030
gsm.sim.operator.iso-country = us,us

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Riru-LocationReportEnabler/blob/master/README.md#customize
