### ISSUE TITLE
更新GoogleAPP后，手机重启卡在锁屏界面

### ISSUE THREAD

**Issue by KempLeung** [RikkaApps/Riru-LocationReportEnabler#15]
设备是一加5T，ROM是LineageOS 16 official 20190304

具体表现为个更新GoogleAPP后，重启手机，输入pin码解锁后，屏幕中间显示手机正在启动，然后一直没反应，放置一段时间后息屏，按电源键无法亮屏，只能长按电源关机后再开启
有时是输入pin码解锁后没反应，一直留在输入pin解锁的界面
上面这两种情况，有个特征就是WIFI图标不亮，正常启动的时候，在进入锁屏界面的时候，WIFI图标已经亮了
因为无法进入系统关闭模块，只能在recovery里面整个magisk卸载掉，这时Google feed又失效了，又得再重新装模块

请问有没更好的办法解决

**Comment by HougeLangley** [comment]
进入 recovery 清第一个和第二个试试
