### ISSUE TITLE
刷入riru两个模块之后Android Q蓝牙fc

### ISSUE THREAD

**Issue by miuifans** [RikkaApps/Riru-LocationReportEnabler#16]
希望早日支持Android Q，thanks！

**Comment by RikkaW** [comment]
提供一下 log 呀（

**Comment by miuifans** [comment]
@RikkaW 莱了莱了～
麻烦大佬看看😛
链接：https://pan.baidu.com/s/12Ta22bD6_z_DHRNslG4LDw 
提取码：btb7

**Comment by imliuruiqi** [comment]
似乎是riru模块的问题，只刷入并启用riru core（17和17.1都是）也会导致蓝牙fc。

**Comment by miuifans** [comment]
> 似乎是riru模块的问题，只刷入并启用riru core（17和17.1都是）也会导致蓝牙fc。

于是我只好把riru模块关了，等后续更新😂

**Comment by morceauai** [comment]
那啥。。。我把模块卸载了，蓝牙还是fc，重刷了magisk也没用，有什么办法不。
