### ISSUE TITLE
安装后地图偏移

### ISSUE THREAD

**Issue by sunxin696** [RikkaApps/Riru-LocationReportEnabler#2]
安装后地图的路线图定位偏移，卫星图却变正确了，这样导致时间轴上记录的地点偏移

**Comment by baraja** [comment]
原因是
gsm.operator.numeric
gsm.operator.iso-country
这两个参数决定是否纠偏，不应该修改成美国的，作者好像弄错了

**Comment by kaedea** [comment]
不修改成美国或者其他地区，就无法开启位置报告了。

**Comment by zfk513** [comment]
@kaedea 咋办 最后只能不用这个功能了吗
