### ISSUE TITLE
安装此模块后在Havoc上无法启用Feed

### ISSUE THREAD

**Issue by hkcnjd** [RikkaApps/Riru-LocationReportEnabler#20]
首先感谢大佬的制作。
我用的手机是pixel2 xl，系统9.0。
之前一直用的官方系统，在安装此模块并登录了google账号后会在通知栏提示位置记录已开启。
Feed和天气也会正常的打开并且刷新。
现在我刷入第三方类原生havoc 9.0ROM后，即使安装此模块也无法打开Feed，一直提示登录账号错误。 经过自己测试很多方法后发现只要插卡便无法正常刷新Feed。
拔卡，清除Google服务，APP等数据后可以正常刷新。但一旦插卡就又不行了。

**Comment by stephenjleng** [comment]
我也是这样。Me too.

**Comment by RikkaW** [comment]
可以试一下 v10（

**Comment by amtoaer** [comment]
尝试使用v10，同样无法刷出feed（Pixel Experience Android 10）
![Screenshot_20201117-151253_Lawnchair.png](https://i.loli.net/2020/11/17/XP1sHWdSz5uwOrh.png)
![Screenshot_20201117-151249758.jpg](https://i.loli.net/2020/11/17/fDbBsrmn8cZT9yE.jpg)

**Comment by amtoaer** [comment]
抱歉，过了半天突然发现可以啦 🤣
