### ISSUE TITLE
MIUI 10 android Q 无法开启location history

### ISSUE THREAD

**Issue by maxfun0** [RikkaApps/Riru-LocationReportEnabler#22]
MIUI 10 android Q 无法开启location history，设置里没有这个选项

**Comment by RikkaW** [comment]
如果是真的没有选项那是傻子 MIUI 的问题

**Comment by SpeedPartner** [comment]
MIUI国内版本需要删掉services.cn.google.xml

**Comment by SpeedPartner** [comment]
其他国行,内置谷歌套件的手机,一般都会有这个,需要删掉才能用.
