### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [RikkaApps/Riru-LocationReportEnabler#23]
`無法在美國使用`

**Comment by 687766616e** [comment]
美國法規問題？

**Comment by 687766616e** [comment]
改成香港的不就行了嗎。。。

**Comment by 687766616e** [comment]
香港也不能！...

**Comment by RikkaW** [comment]
"Can't use in XXX" means LocationReportEnabler had worked. Usually, the Location Report should be recognized as available after clearing the data of Google Play Services or just waiting for a few days.

**Comment by 687766616e** [comment]
ok I'll try it later

**Comment by 687766616e** [comment]
`無法在台灣使用` I can't use that feature everywhere...
