### ISSUE TITLE
大佬可以顺带支持hook下Landroid/provider/Settings$Global吗

### ISSUE THREAD

**Issue by user1121114685** [RikkaApps/Riru-LocationReportEnabler#30]
settings get global op_voice_recording_supported_by_mcc 1

我查遍了api，翻了几个小时源码。也许这个位置可以hook

Settings.CALL_METHOD_GET_GLOBAL

如果可以hook到Settings。 Global 插件可以用来做更多事情。

**Comment by RikkaW** [comment]
这个模块是不会进入 Java 世界的（

**Comment by user1121114685** [comment]
> 这个模块是不会进入 Java 世界的（

也许有不是Java的方法。不过需要去翻源码了。我觉得模块实现的逻辑很好很具有扩展性
