### ISSUE TITLE
建议，为每个程序分配参数。

### ISSUE THREAD

**Issue by user1121114685** [RikkaApps/Riru-LocationReportEnabler#31]
以，$CONFIG_PATH/packages/com.google.android.gsf为例，实际上$CONFIG_PATH/packages/com.google.android.gsf是一个空文件，可以将需要修改的变量放入这个文件实现分应用变量控制。而不需要修改多处，并无法实现分应用控制。

**Comment by RikkaW** [comment]
在不知道多远的以后会出别的东西来做这个

**Comment by user1121114685** [comment]
> 在不知道多远的以后会出别的东西来做这个

就用这个做吧！做出来给模块改个名字就好了。
