### ISSUE TITLE
请问这个要装上后要怎么让它生效呢

### ISSUE THREAD

**Issue by on6hz** [RikkaApps/Riru-LocationReportEnabler#34]
Magisk Manager里显示是开启的没有动过，但是好像没有自己的界面，Google App的Discover也还是空的。

之前也清过Google App的Data和Google Play Services的cache，也重起过手机，飞行也试过了

**Comment by monnerHenster** [comment]
你最后修复成功了吗

**Comment by on6hz** [comment]
> 你最后修复成功了吗

就按照说明在 root.我下面这个APP的文件配置里添加应用到的APP的名称 
最后好像是把双卡取出了，一个以后成功了

**Comment by monnerHenster** [comment]
谢谢提醒，我现在也可以了，双卡要留sim1的位置才行，然后Google now用香港的线路是不显示的，要用对应修改的美国的线路，谢谢！

**Comment by on6hz** [comment]
> 谢谢提醒，我现在也可以了，双卡要留sim1的位置才行，然后Google now用香港的线路是不显示的，要用对应修改的美国的线路，谢谢！

我没有一直用US的，一般Spotify提示要US才能登录才偶尔切一下。
