### ISSUE TITLE
miui 12.5 eu 没有生效

### ISSUE THREAD

**Issue by monnerHenster** [RikkaApps/Riru-LocationReportEnabler#36]
已经安装了magisk22.0 riru riru-location reporten enable,重启后没生效，安装siminfo app并同样添加到config package ，同样没有生效

**Comment by Marblog** [comment]
安装增强模块

**Comment by monnerHenster** [comment]
> 安装增强模块

请问是哪个增强模块，我看到riru剩余的模块中，有xposed增强和ifw增强，感觉都不是。

**Comment by monnerHenster** [comment]
双卡要留sim1的位置才行，然后Google now用香港的线路是不显示的，要用对应修改的美国的线路，问题解决了！

**Comment by monnerHenster** [comment]
解决了。

**Comment by alexiao76** [comment]
> 双卡要留sim1的位置才行，然后Google now用香港的线路是不显示的，要用对应修改的美国的线路，问题解决了！

请问是把Sim1卡槽空出来吗？我也是MIUI 12.5 EU用此模块无效
