### ISSUE TITLE
近两日发现，负1屏Discover、Google Maps里的timeline都不可用了

### ISSUE THREAD

**Issue by ngelee** [RikkaApps/Riru-LocationReportEnabler#37]
感谢作者一直以来的持续更新，让我们能不断bypass各种restriction使用google的各种服务，magisk和riru一直是多年刷机的必备唯二选项。

近日google应该是在背后调整了什么验证机制，负1屏Discover、Google Maps里的timeline又没了。目前只有google的At a Glance的桌面widget中天气图标还能显示，Location History显示为打开。

已经在Pixel 4、Pixel 3 XL上进行了各种常规尝试，包括更新模块到最新版，清除Google、Google Play Service的缓存、数据，退出Google账号全登录，以上操作全部都在路由FQ（vpn地址为美国）的前提下进行，均无效。

恳请作者拨冗检视，感激！

**Comment by Fisummer** [comment]
我的也是失效了，应该是服务端的验证调整导致的，和手机端的任何app更新或设置都无关，因为我多次尝试恢复原厂无法解决问题

**Comment by ngelee** [comment]
嗯，我用Pixel 3 XL刷了3月份的更新包，问题没解决。

如果修改SIM卡信息也么用、而是用定位的话，那估计讨厌了，Google意思以后就算美国佬到中国，一样不能用这些了，够狠。

如果Google只是从别的地方读到了真实的运营商信息，那可能还有希望，毕竟root后一切皆有可能。

**Comment by Fisummer** [comment]
找到我问题的根源了，原来是谷歌把我的代理服务器标记了，虽然用的是美国的代理服务器，不过谷歌估计根据平常搜集到的位置信息调整了，你换个代理服务器试试，应该能解决

**Comment by ngelee** [comment]
你指的是梯子吗？😂Google这么无所不用其极了想给它送钱都没机会。
请问你换的哪个机场？谢谢

**Comment by ngelee** [comment]
换了个日本的服务器，恢复正常了~
