### ISSUE TITLE
应用包名有误？

### ISSUE THREAD

**Issue by oiwl** [RikkaApps/Riru-LocationReportEnabler#6]
谷歌地图的包名是com.google.android.apps.maps
我看介绍里面写的是对的，但是releases页面的包里面的是com.google.android.apps.map（少了个s)
但是结果又能正常工作？

**Comment by RikkaW** [comment]
那应该说明 com.google.android.apps.maps 其实是不需要的吧...（

**Comment by RikkaW** [comment]
确认了一下，如果要开 Google Maps 的时间轴，那 com.google.android.apps.maps 是需要的
