### ISSUE TITLE
Google 时间轴偏移

### ISSUE THREAD

**Issue by kaedea** [RikkaApps/Riru-LocationReportEnabler#7]
时间轴的路线出现了偏移，xp 上面的 drift 插件（通过 hook 住获取 location 的 API 加上偏移量实现）貌似已经失效了，这方面能有解决方案吗？

感觉像是 Google Play Service 获取用户坐标的逻辑，由于 LRE 插件的影响不会走偏移计算逻辑，而 Google 地图应用展现层的数据是有计算偏移量的，所以才出现位置对不上的结果。

**Comment by RikkaW** [comment]
听起来只能凄惨 hook Google Play Service 然后改坐标，这方面（在应用进程动与系统服务交互的部分）还没有一个很优雅的方案（但是有不那么的
所以 凄惨等待..（

**Comment by kaedea** [comment]
Map 应用里面的 UI 元素有的根据坐标做了偏移，有的根据 SIM 卡做了漂移，有的还没做适配 🌚

**Comment by kaedea** [comment]
或者，除了修改SIM，有别的办法启用位置报告吗？

**Comment by RikkaW** [comment]
没有吧..（而且 Rikka 觉得除了 maps 其他的都没有做偏移所以即使能开起来也没有意义（

**Comment by kaedea** [comment]
Timeline 用来记录日常还是挺方便的
