### ISSUE TITLE
地图时间轴功能开启不了

### ISSUE THREAD

**Issue by baraja** [RikkaApps/Riru-LocationReportEnabler#9]
com.google.android.apps.maps 这个包加进去没用，估计谷歌在其他地方也做了对gsm.sim.operator.iso-country的检测
请问应该自定义哪个包能解决这个问题？

**Comment by baraja** [comment]
经测试，v7+v3可以出时间轴，v7+v5不行，v10+v6也不行
系统Android p
Pixel 3 XL

**Comment by eesa** [comment]
V7+V3果然可以，miui10（pie）测试通过

**Comment by baraja** [comment]
> V7+V3果然可以，miui10（pie）测试通过

测下来v10+v3也可以，v3以上都不行，请开发者fix

**Comment by RikkaW** [comment]
然而 v6 比 v3 除了多了可以自定之外没别的区别
什么都不做的话只会多出一个 com.google.android.apps.maps

**Comment by RikkaW** [comment]
发现是 gsm.sim.operator.numeric sm.sim.operator.iso-country 这两个文件多了 \n
试一下 v7 吧

**Comment by NNorLand** [comment]
@RikkaW 大佬，[google-maps-sdk-rectify](https://github.com/oasisfeng/google-maps-sdk-rectify/issues/5)
你看过这个插件的代码吗？能否集成在此模块里面？

**Comment by baraja** [comment]
v7 is working, thx!
